### ISSUE TITLE
Please add an Open Source license

### ISSUE THREAD

**Issue by joergjo** [khalidabuhakmeh/htmx-aspnetcore#1]
It would be great if this repo would include an Open Source license - this is currently mentioned in the [readme](https://github.com/khalidabuhakmeh/htmx-aspnetcore/blob/main/readme.md) file as tdb. Without license, it is not permitted to modify (fork and change) or create derivative work from this repo. 

In my case, I've created a Go version of all examples (except tag helpers), but this version is doomed to rot on my local disk without having that clarity.

**Comment by khalidabuhakmeh** [comment]
Let me check with my overlords, I think I just forgot to add one. Any chance you did those samples using GoLand? :)

**Comment by joergjo** [comment]
Thanks for checking! 

No, I didn't use GoLand, but that can easily be helped... 😜

**Comment by khalidabuhakmeh** [comment]
It's MIT license now. Cheers :)
